# Generated by Django 5.1.1 on 2024-10-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposit',
            new_name='Payment',
        ),
    ]
