# Generated by Django 5.1.1 on 2024-10-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0002_rename_deposit_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='total_debt',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='resident',
            name='move_in_date',
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='move_out_date',
            field=models.DateField(default="3000-01-01"),
            preserve_default=False,
        ),
    ]
