# Generated by Django 5.1.2 on 2024-11-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0003_alter_expense_is_dinner_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
