# Generated by Django 5.1.2 on 2024-10-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0003_rename_total_debt_resident_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerclub',
            name='participants',
            field=models.ManyToManyField(through='kitchenapp.DinnerClubParticipant', to='kitchenapp.resident'),
        ),
        migrations.AlterField(
            model_name='dinnerclub',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kitchenapp.expense'),
        ),
    ]
