# Generated by Django 5.1.2 on 2024-11-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0004_alter_resident_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_dinner_club',
            field=models.BooleanField(default=False),
        ),
    ]
