# Generated by Django 5.1.2 on 2024-11-10 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0005_alter_expense_is_dinner_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerclub',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='kitchenapp.expense'),
        ),
    ]
